# Generated by Django 4.2.27 on 2026-01-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookManager', '0002_delete_login_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
